name: branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  test:
    uses: usafacts/github-workflows/.github/workflows/frontend-library-branch.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
