name: main
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    uses: usafacts/github-workflows/.github/workflows/frontend-library-cjs-main.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
