name: "Auto-Update"
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      GIT_TOKEN:
        required: true
    inputs:
      cleanCheckout:
        description: "Whether to prefer a clean checkout (debug purposes)"
        default: false
        required: false
        type: boolean
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  bumps:
    runs-on: [self-hosted, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: ${{inputs.cleanCheckout}}
          token: ${{secrets.GIT_TOKEN}}
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: update
        continue-on-error: true
        run: |
          git config --global user.email "pipeline@usafacts.org"
          git config --global user.name "Github Pipeline"
          npx npm-check-updates /@usafacts/ --target minor -u
          npx npm-check-updates --target patch -u
      - name: Install
        if: ${{ steps.update.outcome != 'failure' }}
        continue-on-error: false
        run: |
          rm -f package-lock.json
          npm install --legacy-peer-deps
          git add package*
          git commit -m "ci(autoupdate): Auto-update versions [skip ci]"
      - name: Save
        if: ${{ steps.update.outcome != 'failure' }}
        continue-on-error: false
        run: |
          git reset --hard
          git clean -f -d
          git tag -d $(git tag -l)
          git fetch --all --prune
          git push --force
